# Generated by Django 3.1 on 2020-08-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gas_capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='current_gas_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Gas level in %'),
        ),
    ]
