# Generated by Django 3.1 on 2020-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0005_auto_20200820_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='degradation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Tyre Degradation in %'),
        ),
    ]
