# Generated by Django 3.1 on 2020-08-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0007_auto_20200820_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_management.eventtype'),
            preserve_default=False,
        ),
    ]
