# Generated by Django 3.1 on 2020-08-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0008_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelled_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Distance traveled in KM'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total distance to be traveled in KM'),
        ),
    ]
